# see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
name: Bug Report
description: Report a bug in Chichi-ng
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - rreganjr
body:
  - type: dropdown
    id: version
    attributes:
      label: Chichi-ng Version
      description: What version of the library are you running
      options:
        - 2.0.2 (Angular 13)
        - 2.0.1 (Angular 13)
        - 1.1.1 (Angular 8)
        - 1.1.0 (Angular 8)
        - 1.0.3 (Angular 7)
        - 1.0.2 (Angular 7)
        - 1.0.1 (Angular 7)
        - 1.0.0 (Angular 7)
        - not listed
    validations:
      required: true
  - type: textarea
    id: angular-version
    attributes:
      label: Angular Version
      description: what version of angular are you using, run ng version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description what is wrong. Include a link to stackblitz.com if you can.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What behavior were you expecting to see?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What behavior did you actually see?
    validations:
      required: true
